server:
    port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: c-app-products-v1
          uri: http://c-app-products-v1:8081
          predicates:
            - Path=/api/products/**

        - id: c-app-categories
          uri: http://c-app-categories:8082
          predicates:
            - Path=/api/categories/**

      # 👇 Habilita CORS global y maneja preflight (OPTIONS)
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # Evita duplicados si algún servicio también mete CORS
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

  logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web.reactive: DEBUG
        reactor.netty.http.client.HttpClient: DEBUG