services:
  test-db:
    image: mysql:8.0
    container_name: test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [test-network]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin123"]
      interval: 5s
      timeout: 3s
      retries: 10

  c-app-products-v1:
    image: sebraxter/img-product:v15
    container_name: c-app-products-v1
    restart: always
    environment:
      PORT: 8081
      DB_HOST: test-db
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: admin123
    depends_on:
      test-db:
        condition: service_healthy
    networks: [test-network]

  c-app-categories:
    image: sebraxter/img-category:v10
    container_name: c-app-categories
    restart: always
    environment:
      PORT: 8082
      DB_HOST: test-db
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: admin123
    depends_on:
      test-db:
        condition: service_healthy
    networks: [test-network]

  app-gateway:
    image: sebraxter/img-gateway:v2
    container_name: app-gateway
    restart: always
    environment:
      PRODUCTS_URL: http://c-app-products-v1:8081
      CATEGORIES_URL: http://c-app-categories:8082
    depends_on:
      - c-app-products-v1
      - c-app-categories
    networks: [test-network]

  frontend:
    image: sebraxter/img-frontend-tienda:v5
    container_name: angular-frontend
    restart: always
    depends_on:
      - app-gateway
    networks: [test-network]

  edge:
    image: nginx:alpine
    container_name: edge
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./edge.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - app-gateway
    networks: [test-network]

networks:
  test-network:
    driver: bridge

volumes:
  mysql_data: